---

# The following variables will be set by the runner of this playbook:
# src: /tmp/some/path/private_data_dir/
# job_id: <pk>

- hosts: all
  gather_facts: false

  tasks:

    - name: copy artifacts from the isolated host
      synchronize:
        src: "{{src}}/artifacts/"
        dest: "{{src}}/artifacts/"
        mode: pull
        recursive: yes

    - shell: "tower-expect is-alive {{job_id}}"
      register: is_alive
      failed_when: "is_alive.rc == 0"
