---

# The following variables will be set by the runner of this playbook:
# src: /tmp/some/path/private_data_dir/

- hosts: all
  gather_facts: false

  tasks:

    - shell: "tower-expect is-alive {{src}}"
      register: is_alive
      ignore_errors: true

    - name: copy artifacts from the isolated host
      synchronize:
        src: "{{src}}/artifacts/"
        dest: "{{src}}/artifacts/"
        mode: pull
        recursive: yes

    - fail:
        msg: "isolated task is still running"
      when: "is_alive.rc == 0"
