---

# The following variables will be set by the runner of this playbook:
# job_id_cutoff: <pk>

- hosts: all
  gather_facts: false

  tasks:

    - name: Get capacity of the instance
      tower_capacity:
      register: result

    - name: Print capacity in escaped string to scrape out
      debug: msg="{{ start_delimiter|default('') }}{{ result['capacity'] }}{{ end_delimiter|default('') }}"
