---

# The following variables will be set by the runner of this playbook:
# project_path: PROJECTS_DIR/_local_path_
# scm_type: git|hg|svn
# scm_url: https://server/repo
# scm_branch: HEAD
# scm_clean: true/false
# scm_delete_on_update: true/false

- hosts: all
  connection: local
  gather_facts: false
  tasks:

    - name: delete project directory before update
      file: path={{project_path}} state=absent
      when: scm_delete_on_update|default('')

    - name: update project using git
      git: dest={{project_path}} repo={{scm_url}} version={{scm_branch}} force={{scm_clean}}
      when: scm_type == 'git'
      async: 0
      poll: 5

    - name: update project using hg
      hg: dest={{project_path}} repo={{scm_url}} revision={{scm_branch}} force={{scm_clean}}
      when: scm_type == 'hg'
      async: 0
      poll: 5

    - name: update project using svn
      subversion: dest={{project_path}} repo={{scm_url}} revision={{scm_branch}} force={{scm_clean}}
      when: scm_type == 'svn'
      async: 0
      poll: 5
