tower:
  build: ./docker-compose
  ports:
    - "8080:8080"
    - "8013:8013"
  links:
    - postgres
    - redis
    - graphite
  volumes:
    - ../:/tower_devel
postgres:
  image: postgres:9.4.1
  # ports:
  #   - 5432:5432
redis:
  image: redis:3.0.1
  # ports:
  #   - 6379:6379
graphite:
  image: hopsoft/graphite-statsd
  ports:
    - "8001:80"
    - "2003:2003"
    - "8125:8125/udp"
    - "8126:8126"
