version: '3'
services:
  # Primary Tower Development Container link
  awx:
    environment:
      EXTRA_GROUP_QUEUES: thepentagon
    links:
      - isolated
  # Isolated Rampart Container
  isolated:
    image: ${DEV_DOCKER_TAG_BASE}/awx_isolated:${TAG}
    hostname: isolated
    volumes:
      - "../awx/main/isolated:/awx_devel"
      - "../awx/lib:/awx_lib"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true
