version: '3'
services:
  # Primary Tower Development Container link
  awx:
    environment:
      AWX_GROUP_QUEUES: tower,thepentagon
    links:
      - isolated
  # Isolated Rampart Container
  isolated:
    image: gcr.io/ansible-tower-engineering/awx_isolated:${TAG}
    hostname: isolated
    volumes:
      - "../awx/main/isolated:/awx_devel"
      - "../awx/lib:/awx_lib"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true
