---
version: '2'
services:
  unit-tests:
    build:
      context: ../../../
      dockerfile: tools/docker-compose/unit-tests/Dockerfile
    environment:
      SWIG_FEATURES: "-cpperraswarn -includeall -I/usr/include/openssl"
    command: ["make requirements_test test"]

    volumes:
      - ../../../:/ansible-tower
