---
version: '2'
services:
  unit-tests:
    build:
      context: ../../../
      dockerfile: tools/docker-compose/unit-tests/Dockerfile
    image: gcr.io/ansible-tower-engineering/unit-test-runner:${GIT_BRANCH}
    environment:
      SWIG_FEATURES: "-cpperraswarn -includeall -I/usr/include/openssl"
      TEST_DIRS: awx/main/tests/functional awx/main/tests/unit awx/conf/tests awx/sso/tests
    command: ["make test"]
    volumes:
      - ../../../:/tower_devel
